### ISSUE TITLE
Help! 

### ISSUE THREAD

**Issue by lynx29** [agentgonzo/steam-squid#3]
could you help me why im getting this message when opening non https sites.
CacheErrorInfo - ERR_INVALID_URL

**Comment by agentgonzo** [comment]
Could you give me a bit more info please - which URL are you trying to access. If you can also get the logs (in /var/log/squid3 inside the container) for the request then that would also be helpful).

**Comment by lynx29** [comment]
Sorry for late reply! There is no log inside the container but when opening a site using your container what I got is this ( from wireshark )
ET / HTTP/1.1
Host: www.bbc.com
Connection: keep-alive
Cache-Control: max-age=0
Upgrade-Insecure-Requests: 1
User-Agent: Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Ubuntu Chromium/66.0.3359.181 Chrome/66.0.3359.181 Safari/537.36
Accept: text/html,application/xhtml+xml,application/xml;q=0.9,image/webp,image/apng,*/*;q=0.8
Accept-Encoding: gzip, deflate
Accept-Language: en-US,en;q=0.9

HTTP/1.1 400 Bad Request
Server: squid/3.4.8
Mime-Version: 1.0
Date: Tue, 12 Jun 2018 02:09:41 GMT
Content-Type: text/html
Content-Length: 3152
X-Squid-Error: ERR_INVALID_URL 0
Vary: Accept-Language
Content-Language: en
X-Cache: MISS from 67211fbb6cd8
X-Cache-Lookup: NONE from 67211fbb6cd8:3128
Via: 1.1 67211fbb6cd8 (squid/3.4.8)
Connection: close

But using the jpetazzo/squid-in-a-can, It could browse website without a problem. I like to use your container as it could cache steam game downloads.

**Comment by agentgonzo** [comment]
The logs are stored inside the container in /var/log/squid3/, so you can cat/tail them with:
`docker exec steam-squid tail /var/log/squid3/*`. 

I had a look and I think the important part is the line in the response: `server: squid/3.4.8`. That's the response from the actual website, rather than the proxy and is identifying itself as a squid proxy. In my (working requests, I get the response for www.bbc.com as `Server: Apache`.

So as to exactly why this is happening, I'm not sure, but it _looks_ like squid is processing the request, forwarding it to the upstream website, but probably sending it to the wrong place as it's forwarding it to a squid proxy, or squid itself is saying that you've passed it in a bad URL.
I am assuming that you are using a browser given the headers, so can you try it without the browser:

In the command prompt (I'm assuming you're on a windows):


```
set http_proxy=<yourproxy>:3128
curl www.bbc.com -I
```
Valid Response:
```
HTTP/1.1 200 OK
Server: Apache
Content-Type: text/html
Expires: Fri, 15 Jun 2018 08:37:26 GMT
Content-Language: en
ETag: "59d4beb799d12aad5e8ba4ea7553ec58"
X-PAL-Host: pal0122.back.live.cwwtf.local:80
Content-Length: 206649
Date: Fri, 15 Jun 2018 08:36:46 GMT
Set-Cookie: BBC-UID=e54bb2f3078af90ef20cd211f18bc242f33b15c197c444a68a909752ee0603e00curl/7.57.0; expires=Tue, 14-Jun-22 08:36:46 GMT; path=/; domain=.bbc.com
Cache-Control: private, max-age=60
X-Cache-Action: HIT
X-Cache-Hits: 16
X-Cache-Age: 20
X-LB-NoCache: true
Vary: X-CDN,X-BBC-Edge-Cache,Accept-Encoding
X-Cache: MISS from cc2f2a796b29
X-Cache-Lookup: MISS from cc2f2a796b29:3128
Via: 1.1 cc2f2a796b29 (squid/3.4.8)
Connection: keep-alive
```

I managed to recreate your responses with a bad request:
`curl proxy:3128 -H"Host: www.bbc.com" -I`; (incorrectly making the web request to squid, rather than the website)

but in this case, it _is_ an invalid requests, so the response makes sense.
